<h3>Das Klima</h3>
<p>Argentinien  vereint nahezu alle Klima- und Höhenzonen: Von den <a href="http://de.wikipedia.org/wiki/Tropen" title="Tropen">tropischen</a> Regionen im äußersten Nordosten reicht das Land über  subtropische Gebiete im restlichen Norden, von der ausgedehnten gemäßigten  Klimazone zieht es sich hin bis zu kalten Klimaregionen im Süden und in den  Anden.</p>
<p>Der  Nordwesten Argentiniens ist im Bereich der Anden trocken. Hier finden wir  lediglich eine kurze Regenzeit im Sommer. In ihr findet man die Hochwüste <a href="http://de.wikipedia.org/wiki/Puna_(Argentinien)" title="Puna (Argentinien)">Puna</a>, deren  Westen zu den regenärmsten Gebieten der Welt zählt, sowie den steppenhaften,  unfruchtbaren <a href="http://de.wikipedia.org/wiki/Monte_(Argentinien)" title="Monte (Argentinien)">Monte</a> am Fuß  der <a href="http://de.wikipedia.org/wiki/Anden" title="Anden">Anden</a> in den Provinzen <a href="http://de.wikipedia.org/wiki/Mendoza_(Provinz)" title="Mendoza (Provinz)">Mendoza</a>, <a href="http://de.wikipedia.org/wiki/San_Juan_(Provinz)" title="San Juan (Provinz)">San Juan</a> und <a href="http://de.wikipedia.org/wiki/La_Rioja_(Provinz)" title="La Rioja (Provinz)">La Rioja</a>.</p>
<p>Die  Osthänge der Voranden beherbergen subtropische <a href="http://de.wikipedia.org/wiki/Nebelwald" title="Nebelwald">Nebelwälder</a> in den Provinzen <a href="http://de.wikipedia.org/wiki/Tucum%C3%A1n_(Provinz)" title="Tucumán (Provinz)">Tucumán</a>, <a href="http://de.wikipedia.org/wiki/Salta_(Provinz)" title="Salta (Provinz)">Salta</a> und <a href="http://de.wikipedia.org/wiki/Jujuy_(Provinz)" title="Jujuy (Provinz)">Jujuy</a>, die im Sommer wegen des Abregnens der  feuchten Ostwinde sehr niederschlagsreich, im Winter aber relativ trocken sind.  Nach Osten hin schließt sich der <a href="http://de.wikipedia.org/wiki/Gran_Chaco" title="Gran Chaco">Gran Chaco</a> im zentralen Norden an. Seine  Niederschläge konzentrieren sich auf den Sommer. Genauso zeigt sich die  Situation in der Region der <a href="http://de.wikipedia.org/wiki/Sierras_Pampeanas" title="Sierras Pampeanas">Sierras Pampeanas</a> in Zentralargentinien. In  beiden Regionen nehmen die Niederschläge nach Westen hin ab.</p>
<p>Der  Nordosten sowie die <a href="http://de.wikipedia.org/wiki/Pampa" title="Pampa">Pampa</a>-Region sind das ganze Jahr über feucht,  wobei die höchsten Niederschlagsmengen im subtropischen Regenwald der Provinz <a href="http://de.wikipedia.org/wiki/Misiones_(Argentinien)" title="Misiones (Argentinien)">Misiones</a> auftreten.<br>
  Der  Süden (<a href="http://de.wikipedia.org/wiki/Patagonien" title="Patagonien">Patagonien</a>) liegt in der Westwindzone, weshalb  hier der westliche Teil mehr Niederschläge als der Osten erhält. Die Anden sind  ständig feucht und von der Temperatur kühl gemäßigt. Sie wirken als Barriere  für die feuchten Pazifikwinde, so dass das östlich anschließende Gebiet sehr  trocken und halbwüstenhaft ist. In dieser Region bestimmt der regelmäßig alle  ein bis zwei Wochen vom Südwesten her blasende <a href="http://de.wikipedia.org/wiki/Pampero" title="Pampero">Pampero</a>-Wind das Klima. Ein Sonderfall ist das  Klima im südlichen Teil <a href="http://de.wikipedia.org/wiki/Feuerland" title="Feuerland">Feuerlands</a> mit kühlem <a href="http://de.wikipedia.org/wiki/Ozeanisches_Klima" title="Ozeanisches Klima">ozeanischem Klima</a>, wo wegen der dort fehlenden  Klimascheide der Anden sowohl pazifische als auch atlantische Einflüsse das  Wetter bestimmen. Dort sind die Niederschlagsmengen relativ hoch und die  Temperaturen weisen eine relativ geringe Abweichung zwischen Sommer und Winter  auf.</p>
Folgend finden Sie die vier  interesanten Klimadiagramme zu den wohl auch für Sie als Erlebnisreisenden  wichtigen Orten Argentiniens: Salta im Norden, Mendoza im trockenen mittleren  Westen, Buenos Aires an der Atlantkküste und Ushuaia als südlichste Stadt der  Erde.

<div class="backPage"><a href="#" onclick="Slider.slide({url: 'includes/argentinien.php'}, 1); return false;"><img src="images/button_back.png" alt="Volver" title="Volver" border="0" align="absmiddle" />&nbsp;Volver</a></div>
