<h3>Das Klima</h3>

<p>Argentinien vereint nahezu alle Klima- und Höhenzonen: Von den <a href="http://de.wikipedia.org/wiki/Tropen" title="Tropen" target="_blank">tropischen</a> Regionen im äußersten Nordosten reicht das Land über subtropische Gebiete im restlichen Norden, und von der ausgedehnten gemäßigten Klimazone zieht es sich hin bis zu kalten Klimaregionen im Süden und in den Anden.</p>
<p>Der Nordwesten Argentiniens ist im Bereich der Anden trocken. Hier herrscht lediglich eine kurze Regenzeit im Sommer. In ihr finden wir die Hochandenwüste der <a href="http://de.wikipedia.org/wiki/Puna_(Argentinien)" title="Puna (Argentinien)" target="_blank">Puna</a>, deren Westen zu den regenärmsten Gebieten der Welt zählt, sowie den steppenhaften, unfruchtbaren <a href="http://de.wikipedia.org/wiki/Monte_(Argentinien)" title="Monte (Argentinien)" target="_blank">Monte</a> am Fuß der <a href="http://de.wikipedia.org/wiki/Anden" title="Anden" target="_blank">Anden</a> in den Provinzen <a href="http://de.wikipedia.org/wiki/Mendoza_(Provinz)" title="Mendoza (Provinz)" target="_blank">Mendoza</a>, <a href="http://de.wikipedia.org/wiki/San_Juan_(Provinz)" title="San Juan (Provinz)" target="_blank">San Juan</a> und <a href="http://de.wikipedia.org/wiki/La_Rioja_(Provinz)" title="La Rioja (Provinz)" target="_blank">La Rioja</a>.</p>
<p>Die Osthänge der Voranden beherbergen subtropische Regen- und <a href="http://de.wikipedia.org/wiki/Nebelwald" title="Nebelwald" target="_blank">Nebelwälder</a> in den Provinzen <a href="http://de.wikipedia.org/wiki/Tucum%C3%A1n_(Provinz)" title="Tucumán (Provinz)" target="_blank">Tucumán</a>, <a href="http://de.wikipedia.org/wiki/Salta_(Provinz)" title="Salta (Provinz)" target="_blank">Salta</a> und <a href="http://de.wikipedia.org/wiki/Jujuy_(Provinz)" title="Jujuy (Provinz)" target="_blank">Jujuy</a>, die im Sommer wegen des Abregnens der feuchten Ostwinde sehr niederschlagsreich, im Winter aber relativ trocken sind. Nach Osten hin schließt sich der <a href="http://de.wikipedia.org/wiki/Gran_Chaco" title="Gran Chaco" target="_blank">Gran Chaco</a> im zentralen Norden an. Seine Niederschläge konzentrieren sich auf den Sommer. Genauso zeigt sich die Situation in der Region der <a href="http://de.wikipedia.org/wiki/Sierras_Pampeanas" title="Sierras Pampeanas" target="_blank">Sierras Pampeanas</a> in Zentralargentinien. In beiden Regionen nehmen die Niederschläge nach Westen hin ab.</p>
<p>Der Nordosten sowie die <a href="http://de.wikipedia.org/wiki/Pampa" title="Pampa" target="_blank">Pampa</a>-Region sind das ganze Jahr über feucht, wobei die höchsten Niederschlagsmengen im subtropischen Regenwald der Provinz <a href="http://de.wikipedia.org/wiki/Misiones_(Argentinien)" title="Misiones (Argentinien)" target="_blank">Misiones</a> auftreten.</p>
<p>Der Süden (<a href="http://de.wikipedia.org/wiki/Patagonien" title="Patagonien" target="_blank">Patagonien</a>) liegt in der Westwindzone, weshalb hier der westliche Teil mehr Niederschläge als der Osten erhält. Die Anden sind ständig feucht und von der Temperatur kühl gemäßigt. Sie wirken als Barriere für die feuchten Pazifikwinde, so dass das östlich anschließende Gebiet sehr trocken und halbwüstenhaft ist. In dieser Region bestimmt der regelmäßig alle ein bis zwei Wochen vom Südwesten her blasende <a href="http://de.wikipedia.org/wiki/Pampero" title="Pampero" target="_blank">Pampero</a>-Wind das Klima. Ein Sonderfall ist das Klima im südlichen Teil <a href="http://de.wikipedia.org/wiki/Feuerland" title="Feuerland" target="_blank">Feuerlands</a> mit kühlem <a href="http://de.wikipedia.org/wiki/Ozeanisches_Klima" title="Ozeanisches Klima" target="_blank">ozeanischen Klima</a>, wo wegen der dort fehlenden Klimascheide der Anden sowohl pazifische als auch atlantische Einflüsse das Wetter bestimmen. Dort sind die Niederschlagsmengen relativ hoch und die Temperaturen weisen eine relativ geringe Abweichung zwischen Sommer und Winter auf.</p>
<p>Folgend finden Sie die vier interesanten Klimadiagramme zu den wohl auch für Sie als Erlebnisreisenden wichtigen Orten Argentiniens: Salta im Norden, Mendoza im trockenen mittleren Westen, Buenos Aires an der Atlantkküste und Ushuaia als südlichste Stadt der Erde.</p>

<p><img src="images/graficos/graf1.jpg" alt="" width="489" height="337" border="1" /><br /><b>Klimadiagramm Salta Stadt</b></p>
<p><img src="images/graficos/graf2.jpg" alt="" width="489" height="337" border="1" /><br /><b>Klimadiagramm Mendoza Stadt</b></p>
<p><img src="images/graficos/graf3.jpg" alt="" width="489" height="337" border="1" /><br /><b>Klimadiagramm Buenos Aires Stadt</b></p>
<p><img src="images/graficos/graf4.jpg" alt="" width="489" height="337" border="1" /><br /><b>Klimadiagramm Ushuaia</b></p>


<div class="backPage"><a href="#" onclick="Slider.slide({url: 'includes/argentinien.php'}, 1); return false;"><img src="images/button_back.png" alt="Volver" title="Volver" border="0" align="absmiddle" />&nbsp;Volver</a></div>
