<h3>Die Provinz</h3>

<p>Mendoza ist eine Provinz im zentralen Westen von <a href="http://de.wikipedia.org/wiki/Argentinien" title="Argentinien" target="_blank">Argentinien</a>. Ihre Nachbarn sind die Provinzen <a href="http://de.wikipedia.org/wiki/San_Juan_(Provinz)" title="San Juan (Provinz)" target="_blank">San Juan</a> im Norden, <a href="http://de.wikipedia.org/wiki/San_Luis_(Provinz)" title="San Luis (Provinz)" target="_blank">San Luis</a> und <a href="http://de.wikipedia.org/wiki/La_Pampa" title="La Pampa" target="_blank">La Pampa</a> im Osten, <a href="http://de.wikipedia.org/wiki/R%C3%ADo_Negro_(Provinz)" title="Río Negro (Provinz)" target="_blank">Río Negro</a> und <a href="http://de.wikipedia.org/wiki/Neuqu%C3%A9n_(Provinz)" title="Neuquén (Provinz)" target="_blank">Neuquén</a> im Süden und der <a href="http://de.wikipedia.org/wiki/Chile" title="Chile" target="_blank">Chile</a> im Westen. Die Provinzhauptstadt befindet sich 1.100 km von Buenos Aires, 350 km von Santiago de Chile und 400 km vom Pazifikhafen Valparaiso entfernt.</p>
<p>Der größte Teil der Provinz liegt, nebem dem sehr gebirgigen Andenbereich in einer Trockensteppe, dem <a href="http://de.wikipedia.org/wiki/Monte_(Argentinien)" title="Monte (Argentinien)" target="_blank">Monte</a>, die teilweise wie im nordöstlichen Departamento Lavalle durch kleine Sandwüsten unterbrochen wird. Das Bild der Provinz wird durch drei große Oasen bestimmt, was man sehr gut über „Google-Earth“ nachvollziehen kann: die nördliche mit der Provinzhauptstadt Mendoza, eine mittlere um die Städte <a href="http://de.wikipedia.org/wiki/San_Rafael_(Argentinien)" title="San Rafael (Argentinien)">San Rafael</a> und <a href="http://de.wikipedia.org/w/index.php?title=General_Alvear&action=edit&redlink=1" title="General Alvear (Seite nicht vorhanden)">General Alvear</a> und eine südliche rund um die Stadt <a href="http://de.wikipedia.org/wiki/Malarg%C3%BCe" title="Malargüe">Malargüe</a>. Der Westen der Provinz demonstriert das imponierende Schauspiel der sehr rasch ansteigenden Pre-Cordillere mit über 3.000 m, die, nach dem Längstal des Río Mendoza und der Stadt Uspallata, in die Cordillere Principal der <a href="http://de.wikipedia.org/wiki/Anden" title="Anden">Anden</a> zu ihrer höchsten Erhebung, den <a href="http://de.wikipedia.org/wiki/Aconcagua" title="Aconcagua">Aconcagua</a>, ansteigt. Dort befindet sich auch das Naturphänomen „<a href="http://de.wikipedia.org/wiki/Puente_del_Inca" title="Puente del Inca">Puente del Inca</a>“; eine durch Flussunterspülung bei gleichzeitiger und massiver Kalkausfällung aus einer am Berghang darüber liegenden Quelle zu einer natürlich entstandenen Brücke über den Río Mendoza führt.</p>
<p>Das Klima ist im gesamten Provinzterritorium trocken, sonnig und kontinental, mit sehr heissen Sommern und relativ kalten Wintern. Trotz dieser Kontinentalität bleiben starke Temperaturunterschiede zwischen Tag und Nacht jedoch aus. Das heisst, das wir in den Monaten Dezember bis März sehr wohl maximale Temperaturen von über 35°C am Tag und nur schwache Absenkungen bis vielleicht unter 25°C vor allem im Städteagglommerat Mendoza feststellen können. Die jährliche Niederschlagsmenge liegt zwischen 100 und 350 Millimetern. Im Winter melden die Thermomter um die 15°C am Tag und bis wenige Grade unter Null nachts.</p>
<p>Die Provinz hat bei einer Ausdehnung von ca. 150.000 km2 und einer geschätzten Bevölkerungszahl von derzeit 2,3 Mio Einwohnern, eine mittlere Bevölkerungsdichte von 15 Einwohnern/km2. Die Einwohner konzentrieren sich jedoch in den drei Oasen. Wichtige Städte sind die Provinzhauptstadt Mendoza (ca. 1.500.000 Einwohner), San Rafael (180.000 Einwohner) im mittleren Süden und San Martín de Mendoza (130.000 Einwohner) im Osten. Der äußerste Süden ist sehr dünn besiedelt; einziger Ort von Bedeutung ist Malargüe (35.000 Einwohner).</p>

<p>Die Wirtschaft Mendozas dreht sich zum grossen Teil um die Landwirtschaft, bei der <a href="http://de.wikipedia.org/wiki/Weinbau" title="Weinbau" target="_blank">Weinbau</a>, Knoblauch, Oliven und Obst herausragen. Der Weinbau verschafft Mendoza Weltruhm und den 4. Platz unter den Weinproduzenten in der Welt mit ausgezeichneten Erzeugnissen. </p>
<p>Weiterhin ist die Erdöl- und Gasförderung von Bedeutung (Raffinerie in Luján de Cuyo). Der Bergbau soll in naher Zukunft eine Vorreiterposition einnehmen. Die Wirtschaftsmetropole kann ihre Bedeutung halten, da Mendoza den wichtigsten Andenpass für den Güteraustausch zwischen Atlantik (Mercosur-Staaten) und Pazifik (Asien) darstellt. </p>
<p>Auf diese Situation sind die Wirtschaftsstrukturen mit einer breiten Palette an Dienstleistungen ausgerichtet. Auch die Verkehrsanbindungen national und international nach Brasilien reflektieren diese Zentralfunktion. </p>

<div class="backPage"><a href="#" onclick="Slider.slide({url: 'includes/argentinien.php'}, 1); return false;"><img src="images/button_back.png" alt="Volver" title="Volver" border="0" align="absmiddle" />&nbsp;Volver</a></div>
