<h3>Die Soziale Struktur Argentiniens</h3>

<p>Die soziale Situation des Landes ist in mehrerer Hinsicht durch eine starke Ungleichheit gekennzeichnet. Es gibt ein sehr ausgeprägtes Wohlstandsgefälle zwischen Ober- und sozialer Unterschicht. So gehören die argentinischen Top-Manager-Gehälter zu den höchsten in Südamerika, während die ärmsten und 50 % der Bezölkerung sich mit nur zehn Prozent des gesamten <a href="http://de.wikipedia.org/wiki/Volkseinkommen" title="Volkseinkommen" target="_blank">Volkseinkommens</a> zufrieden geben müssen.</p>
<p>Aber auch die Unterschiede zwischen den Regionen Argentiniens sind groß. So liegt etwa die Armutsrate, die nach einem Warenkorb berechnet wird, in der Hauptstadt <a href="http://de.wikipedia.org/wiki/Buenos_Aires" title="Buenos Aires" target="_blank">Buenos Aires</a> mit etwa 15 % nur etwas mehr als halb so hoch wie im Landesdurchschnitt (23 %), während sie in der Nordostregion bei 41 % liegt (Stand 2007). Eine Durchschnittsperson benötigte im März 2008 monatlich etwa 317,- argentinische Pesos, um nicht unter die Armutslinie zu fallen. In den meisten Haushalten ist es daher nötig, dass mehrere Familienmitglieder zum Einkommen beitragen. Dies zeigt auch die offizielle Statistik: So liegt das durchschnittliche monatliche Pro-Kopf-Einkommen bei etwa 1.156,- argentinischen Pesos und damit nur knapp über der Armutsrate für Familien, während das durchschnittliche monatliche Haushaltseinkommen bei 2.090,- argentinische Pesos liegt.</p>
<p>Generell kann man sagen, dass die nördlichen Provinzen, besonders die Provinz <a href="http://de.wikipedia.org/wiki/Tucum%C3%A1n_(Provinz)" title="Tucumán (Provinz)" target="_blank">Tucumán</a> und der Nordosten (<a href="http://de.wikipedia.org/wiki/Chaco_(Provinz)" title="Chaco (Provinz)" target="_blank">Chaco</a>, Formosa, <a href="http://de.wikipedia.org/wiki/Santiago_del_Estero_(Provinz)" title="Santiago del Estero (Provinz)" target="_blank">Santiago del Estero</a>) am stärksten von Armut und Unterernährung betroffen sind. Verschärft wird diese Situation durch das relativ schnelle Bevölkerungswachstum in dieser Region. Als relativ reich dagegen gelten die zentralen Provinzen (<a href="http://de.wikipedia.org/wiki/Buenos_Aires_(Provinz)" title="Buenos Aires (Provinz)" target="_blank">Buenos Aires</a>, <a href="http://de.wikipedia.org/wiki/Santa_Fe_(Provinz)" title="Santa Fe (Provinz)" target="_blank">Santa Fe</a>, <a href="http://de.wikipedia.org/wiki/C%C3%B3rdoba_(argentinische_Provinz)" title="Córdoba (argentinische Provinz)" target="_blank">Córdoba</a>, <a href="http://de.wikipedia.org/wiki/San_Luis_(Provinz)" title="San Luis (Provinz)" target="_blank">San Luis</a> und <a href="http://de.wikipedia.org/wiki/Mendoza_(Provinz)" title="Mendoza (Provinz)" target="_blank">Mendoza</a>), aber auch der äußerste Süden (<a href="http://de.wikipedia.org/wiki/Santa_Cruz_(Argentinien)" title="Santa Cruz (Argentinien)" target="_blank">Santa Cruz</a> und <a href="http://de.wikipedia.org/wiki/Tierra_del_Fuego_(Argentinien)" title="Tierra del Fuego (Argentinien)" target="_blank">Tierra del Fuego</a>).</p>

<p>Es sind neben den grenznahen Gegenden (beispielsweise <a href="http://de.wikipedia.org/wiki/Jujuy_(Provinz)" title="Jujuy (Provinz)" target="_blank">Jujuy</a> und Formosa) vor allem die reichen Zentralprovinzen, die am stärksten mit der städtischen Armut und damit mit der <a href="http://de.wikipedia.org/wiki/Slum" title="Slum" target="_blank">Slumbildung</a> zu kämpfen haben. Die Zuwanderung aus den ärmeren Nachbarländern <a href="http://de.wikipedia.org/wiki/Peru" title="Peru" target="_blank">Peru</a>, <a href="http://de.wikipedia.org/wiki/Bolivien" title="Bolivien" target="_blank">Bolivien</a> und Paraguay sowie die Binnenwanderung aus abgelegenen Gegenden des Landesinneren sind trotz einer Abschwächung in den 1990er Jahren in den Grossstädten immer noch ein großes Problem, das die Zahl der Slumbewohner trotz sozialer Wohnungsprogramme weiterhin anwachsen lässt. So liegt beispielsweise in <a href="http://de.wikipedia.org/wiki/Rosario" title="Rosario" target="_blank">Rosario</a> der Anteil der Slumbewohner an der Gesamtbevölkerung bei über 15 %. Es addierte sich Zuwachs in den Slums auch von den so genannten Neu-Armen, besonders in den wirtschaftlich kritischen Jahren 1989/1990, 1995 sowie zwischen 1998 und 2002.</p>
<p>In der <a href="http://de.wikipedia.org/wiki/Argentinien-Krise" title="Argentinien-Krise" target="_blank">Argentinien-Krise</a> verschlechterten sich viele Indikatoren der sozialen Situation in kürzester Zeit, insbesondere in den Jahren 2001 und 2002, in denen die Armutsrate, die nach einem Warenkorb berechnet wird, auf über 50 % stieg. Ab 2003 normalisierten sich die Werte langsam wieder, allerdings bleibt die Armutsrate trotz eines deutlichen Rückgangs weiterhin mit über 20 % deutlich über den Werten der 1990er Jahre. Dabei sind in der am stärksten betroffenen <a href="http://de.wikipedia.org/wiki/Regi%C3%B3n_Noreste_Argentino" title="Región Noreste Argentino" target="_blank">Región Noreste Argentino</a> (Nordostregion) weiterhin fast die Hälfte der Bevölkerung arm. Für 2009 sprach man wieder von ca. 50 % Armut in Argentinien.</p>

<div class="backPage"><a href="#" onclick="Slider.slide({url: 'includes/argentinien.php'}, 1); return false;"><img src="images/button_back.png" alt="Volver" title="Volver" border="0" align="absmiddle" />&nbsp;Volver</a></div>
