<h3>Die Stadt</h3>

<p>Mendoza liegt auf durchschnittlich 900 Metern Höhe im zentralen Westen Argentiniens und direkt am Fuß der Cordillera de Los <a href="http://de.wikipedia.org/wiki/Anden" title="Anden">Andes</a>, die an dieser südlichen Breite die höchsten Erhebungen (Cerro <a href="http://de.wikipedia.org/wiki/Aconcagua" title="Aconcagua">Aconcagua</a>: 6962 m) aufweist; und nur ca. 80 km von Mendoza entfernt liegt (6.200 m auf 80 km Distanz). Die Landschaft um die städtische Siedlungsausdehnung ist eine karge Trockensteppe, die aber innerhalb und in der unmittelbaren Umgebung der Stadt bewässert wird, so dass Weinbau, Olivenzucht und intensiver Ackerbau möglich wird. Der aus den Anden kommende Río Mendoza wird vor den Toren der Stadt zu 100 % aufgestaut, in ein System mit zahllose Bewässerungsgräben aufgezweigt und auch als Trinkwasser konsumiert. Das Klima ist trocken, sonnig und von den Temperaturverhältnissen aus betrachtet im Durchschnitt gemäßigt warm bis heiss. </p>
<p>Die Stadt wurde 1561 von <a href="http://de.wikipedia.org/w/index.php?title=Pedro_del_Castillo&action=edit&redlink=1" title="Pedro del Castillo (Seite nicht vorhanden)">Pedro del Castillo</a> gegründet und nach <a href="http://de.wikipedia.org/wiki/Garc%C3%ADa_Hurtado_de_Mendoza" title="García Hurtado de Mendoza">García Hurtado de Mendoza</a>, dem damaligen Gouverneur von Chile benannt. Sie blieb aber lange eine unbedeutende Kleinstadt.</p>
<p>Im Jahre 1817 brach General <a href="http://de.wikipedia.org/wiki/Jos%C3%A9_de_San_Mart%C3%ADn" title="José de San Martín">José de San Martín</a>, seit 1813 Gouverneur von Cuyo, in Las Heras, ein Departamento von Mendoza, mit seiner Revolutionsarmee auf, um die Anden zu überqueren und für die Befreiung Chiles und Perus von der Kolonialherrschaft der Spanier zu kämpfen.</p>
<p>Am 20. März 1861 zerstörte ein <a href="http://de.wikipedia.org/wiki/Erdbeben" title="Erdbeben">Erdbeben</a> die Stadt vollständig, so dass heute aus der Kolonialzeit nur noch die Ruinen der Kirche des Hl. Franziskus erhalten sind. Bei dem Beben mussten etwa 10.000 der 18.600 Einwohner, also rund die Hälfte der Bewohner, ihr Leben lassen. Zwei Jahre später wurde die Stadt erneut aufgebaut. Man hatte allerdings die enorme Weitsicht, die Stadt aus Gründen der urbanen Gesundheit und Sicherheit so weiträumig neu zu organisieren, dass wir heute ein Konzept einer modernen Stadtplanung vor uns haben, das sogar dem aktuellen und kaotischen Strassenverkehr Herr wird. Das heisst, dass die Strassen selbst als Fluchtwege und für Zufluchtsorte bei Erdbeben sehr breit angelegt sind. Die gemessene halbe Distanz der Breite der Stassen wurde als Breite für die Gehsteige übertragen; und zwischen den Gehsteigen und den Strassen wurden Bewässerungsgräben, sogenannte „acequias“ angelegt, die die Bäume bewässern, die sich entlang zur rechten und Linken jeder Stasse der Stadt aneinanderreihen. Sie können sich vorstellen, dass sich bei dieser grosszügigen Struktur sehr schnell die Kultur und das Bild der heutigen überall verbreiteten Stassencafés einstellte. Das mediterrane Flair Mendozas basiert somit auf den langen bisweilen heissen Sommermonaten, gepaart mit den breiten und beschatteten Strassen und deren Cafés.</p>
Bekannteste Veranstaltung in der Stadt ist das nationale Fest der <a href="http://de.wikipedia.org/wiki/Weinlese" title="Weinlese">Weinlese</a>, „la vendimia“, welches seit 1936 im Sommer und Frühherbst jedes Jahres über drei Monate hinweg stattfindet. Die Festlichkeiten erreichen ihren Höhepunkt im März, wenn im Amphitheater von Mendoza im Parque General San Martín Musik- und Tanzveranstaltungen stattfinden, und eine nationale Weinkönigin aus den Kandidatinnen der verschiedenen Departamentos der Provinz gewählt wird.

<div class="backPage"><a href="#" onclick="Slider.slide({url: 'includes/argentinien.php'}, 1); return false;"><img src="images/button_back.png" alt="Volver" title="Volver" border="0" align="absmiddle" />&nbsp;Volver</a></div>
