<h3>Fachpraktika</h3>
<ul>
<li><a href="#" onclick="Slider.slide({url: 'includes/secciones/wer-kann-an-unserem-programm-teilnehmen.php?returnpage=fachpraktika.php'}, 2); return false;"><img src="images/iconos/quien_puede_participar.png" alt="" border="0" /> Wer kann an unserem Programm teilnehmen</a></li>
<!--<li><a href="#" onclick="Slider.slide({url: 'includes/secciones/anmeldeverfahren-formulare-fur-antrage-und-anmeldungen.php?returnpage=fachpraktika.php'}, 3); return false;"><img src="images/iconos/procedimiento_de_inscripcion_formularios.png" alt="" border="0" /> Anmeldeverfahren - Formulare f&uuml;r Antr&auml;ge und Anmeldungen</a></li>-->
<li><a href="#" onclick="Slider.slide({url: 'includes/secciones/download-des-anmeldeformulares.php?returnpage=fachpraktika.php'}, 5); return false;"><img src="images/iconos/download_formularios.png" alt="" border="0" /> Anmeldeformulare</a></li>
<li><a href="#" onclick="Slider.slide({url: 'includes/secciones/ihre-anreise.php?returnpage=fachpraktika.php'}, 6); return false;"><img src="images/iconos/su_viaje_de_ida.png" alt="" border="0" /> Ihre Anreise</a></li>
<li><a href="#" onclick="Slider.slide({url: 'includes/secciones/ihre-unterkunft.php?returnpage=fachpraktika.php'}, 7); return false;"><img src="images/iconos/su_hospedaje.png" alt="" border="0" /> Ihre Unterkunft</a></li>
<li><a href="#" onclick="Slider.slide({url: 'includes/secciones/wie-geht-es-weiter.php?returnpage=fachpraktika.php&filename=Preisliste_2010_Green_Fields2.html'}, 8); return false;"><img src="images/iconos/como_seguir.png" alt="" border="0" /> Wie geht es weiter mit den Fachpraktika?</a></li>
<li><a href="#" onclick="Slider.slide({url: 'includes/secciones/nicht-im-preis-enthalten.php?returnpage=fachpraktika.php'}, 9); return false;"><img src="images/iconos/lo_que_no_esta_dentro_del_precio.png" alt="" border="0" /> Nicht im Preis enthalten</a></li>
<!--<li><a href="#" onclick="Slider.slide({url: 'includes/secciones/zahlungsmodalitaten.php?returnpage=fachpraktika.php'}, 10); return false;"><img src="images/iconos/modalidades_pago.png" alt="" border="0" /> Zahlungsmodalit&auml;ten</a></li>-->
<li><a href="store/BEWERBUNGSABLA-UF-Praktikas-und-Voluntariat.doc"><img src="images/iconos/procedimiento_de_inscripcion_formularios.png" alt="" border="0" /> Bewerbungsablauf Praktikas und Voluntariat; Zahlungsmodalit&auml;ten</a></li>
<li><a href="javascript:void(open_popup('lista_de_voluntariado_y_pasantia.html'))"><img src="images/iconos/lista_cursos_espanol_costos.png" alt="" border="0" /> Liste für Praktikas und Freiwilligenarbeit</a></li>
<li><a href="#" onclick="Slider.slide({url: 'includes/secciones/vertraulichkeitserklarung.php?returnpage=fachpraktika.php'}, 11); return false;"><img src="images/iconos/declaracion_confidencialidad.png" alt="" border="0" /> Vertraulichkeitserkl&auml;rung</a></li>
</ul>