<h3>Kulturelle Beziehungen</h3>
<p>Deutsche  Kultur der Vergangenheit und Gegenwart genießt beträchtliches Ansehen in  Argentinien und ist im Kulturleben präsent. Die  kulturelle Zusammenarbeit fußt auf der Grundlage des deutsch-argentinischen  Kulturabkommens von 1973.&nbsp;<br>
Argentinien  ist ein Schwerpunktland der Hochschulzusammenarbeit. Der in Buenos Aires mit  einem Informationszentrum vertretene DAAD verfügt im Bereich  Wissenschaftleraustausch und Stipendienprogramme über vielfältige  Kooperationsvereinbarungen mit Regierungsstellen und privaten argentinischen Stiftungen.  Vom DAAD finanziert, befinden sich ferner insgesamt 8 entsandte Fachkräfte, 7  Lektoren sowie ein Lehrstuhlinhaber (Walter-Gropius-Lehrstuhl an der Fakultät  für Architektur) im Land. Zwischen Universitäten beider Länder bestehen rund 45  Kooperationen unterschiedlicher Intensität, bis hin zu einem integrierten  Studiengang mit Abschlüssen an beiden Hochschulen. Zur Zeit befindet sich das  erste deutsch-argentinische Postgraduierten-Programm im Aufbau. Die Universität  Freiburg und die Universität von Buenos Aires (UBA, mit über 330.000 Studenten  die zweitgrößte Latein-Amerikas) haben ein internationales Masterprogramm in  Biomedizin aufgebaut.&nbsp;<br>
Die  Max-Planck-Gesellschaft hat im November 2007 ihr weltweit zweites binationales  Forschungsinstitut in Argentinien aus der Taufe gehoben. Argentinien ist  aufgrund der gut ausgebildeten Professoren und Studenten ein hoch interessanter  Partner im akademischen Bereich. Die Mittelzuwächse der jüngsten Zeit haben das  deutsche Interesse an Zusammenarbeit zusätzlich gefördert und  erleichtert.&nbsp;&nbsp;<br>
Die  beiden deutschen Kulturinstitute (Goethe Institut) in Buenos Aires und Goethe  Zentrum in Córdoba bieten ein breit gefächertes Kulturprogramm, das Einblicke  in das aktuelle deutsche Kulturgeschehen gewährt. Ergänzt wird dieses  Engagement durch die Aktivitäten von über 12 deutsch-argentinischen  Kulturgesellschaften im ganzen Land.&nbsp;<br>
In  Argentinien gibt es 19 von Deutschland geförderte Schulen, an denen 15.559  Schüler unterrichtet werden. Das deutsch-argentinische Regierungsabkommen über  die deutschen Schulen von 1997 - das erste seiner Art mit einem anderen Staat -  trägt diesem Umstand Rechnung. &nbsp;Zusätzliche 90 Schulen im  Land unterrichten Deutsch.</p>
(Quelle: Auswärtiges Amt)

<div class="backPage"><a href="#" onclick="Slider.slide({url: 'includes/argentinien.php'}, 1); return false;"><img src="images/button_back.png" alt="Volver" title="Volver" border="0" align="absmiddle" />&nbsp;Volver</a></div>
