<h3>Spanisch lernen in Mendoza</h3>
  <p>Die  einfachste Weise, Spanisch zu lernen, und dabei die erlebnisreichste, aber auch  gleichzeit mit viel Spass, ist diejenige, das alltägliche Leben mit den  Einheimischen in ihrer geographischen und sozialen Umgebund zu teilen. Bei  diesem Vorzug geniessen Sie z.B. die besten Steaks der Welt während eines  „Asados“ mit Freunden, Geschichten über die unendlichen Weiten der Anden bei „Mate“-Tee,  bis hin zu Weinproben in einer der über 1.000 Weinbaubetrieben der Oase von  Mendoza. Sie sind bei ausgesuchten und für diese Aufgabe motivierten Familien  in Mendoza zu Gast, werden daher sogar bald in spanischer Sprache denken und  vervollkommnen diese Erfahrung begleitet durch einen intensiven und speziell  auf Ihre Bedürfnisse und Wünsche zugeschnittenen Sprachkurs in unserem Sprach-  und Kultur-Institut GREEN FIELDS.   Sprach- und Kultur-Institut bedeutet, dass neben der intensiven und  einprägsamen, aber gleichzeitig unterhaltsamen Sprachübermittlung, unmittelbar  kulturelle und soziale Inhalte des täglichen Geschehens in das Übungsprogramm  eingeflochten sind.     </p>
  <p>Die  Spanischkurse können kurzfristig von Jedermann als reiner Sprachkurs gebucht  werden, ohne Teilnahme an einer Freiwilligenarbeit, einem studentischen oder  professionellem Praktikum oder einem Universitätsaufenthalt.</p>
  <p>Green  Fields bietet ein variiertes Kursangebot, das auf die Schüler und  Kursteilnehmer zugeschnitten ist. Die Kursniveaus orientieren sich am  europäischen Rahmen (Common  European Framework of Reference for Languages). Der Unterricht bietet folgende  Formate:<br />
    - One to one  (Individualunterricht)<br />
    - Two to one (Zwei Schüler/Teilnehmer einem Lehrer)<br />
    - Gruppal (reduzierte Gruppen von drei bis maximal  10 Schüler/Teilnehmer)<br />
    Kosten:<br />
    - One to one: eine Unterrichtsstunde zu 55 Minuten =  13,- Euro<br />
    - Two to one: eine Unterrichtsstunde zu 55 Minuten =  20,- Euro (10,- Euro pro Schüler)<br />
    In jedem Fall bezahlen Sie pro Person 30,- Euro für  Einschreibungsgebühren je Programm.</p>
  <p>Die Kurse sind im Blockunterricht zu 20 Stunden pro  Woche aufgebaut. In allen Fällen beinhalten die Kurse das notwendige  Unterrichtsmaterial, freien Internetzugang während des Aufenthalts im Sprach- und  Kultur-Institut GREEN FIELDS und das Überlebenshandhuch „Vademecum in Mendoza“  für unsere Teilnehmer.</p>
  <p>Sämtliche  Kurse beginnen am Montag jeder Woche und finden ganzjährig statt. Der Schüler  muss sich mindestens für einen Kurs zu 20 Wochenstunden inmatrikulieren, um ein  Programm iniziieren zu können. Anschliessend kann er wahlweise und je nach  seinen individuellen  Neigungen und  Notwendigkeiten seine Studien ausdehnen oder aber auch ausscheiden. Das heisst,  er kann blockweise mit Kursen zu 20 Wochenstunden fortfahren oder sich für  Kurse für spezielle und spezifischer Voraussetzungen entscheiden (siehe „Unser  umfangreiches Angebot im Einzelnen“). Die Kurse können wochenweise von 1 – 12  Wochen Dauer gebucht werden. </p>
  <p>Zu Ihrer Kurzinformation:</p>
  <p>Was ist ein Grundkurs?<br />
    Grundelemente der Kommunikation um sich als Tourist  in der Stadt und auf Reisen gut fortbewegen zu können. Der Kurs beinhaltet  Unterrichtsmaterial und sprachliche, schriftliche sowie audi-visuelle Übungen,  die die Dialoge des täglichen Geschehens widerspiegeln. Dieser  Kurs ist auf das Niveau eines jeden  Teilnehmers zugeschnitten; das heisst, grundlegend mit oder ohne Vorkenntnisse,  mit vorhandenen Grundkenntnissen oder für Fortgeschrittene.</p>
  <p>Was ist ein Spezialkurs von 4 Wochen?<br />
    Dies sind Kurse von midestens 4 Wochen Dauer über  die der Teilnehmer sich die fundamentalen und notwendigen Werkzeuge aneignet,  um sich auf den unterschiedlichen Bühnen seiner Interessen bewegen zu können:  Universitätsstudium, Studenten- und Berufspraktika und Freiwilligenarbeit nach  individueller Wahl. Bei Interesse kann der Teilnehmer natürlich auch sein  Programm ausweiten bzw. nach seinen Bedürfnissen und gewünschten Inhalten  verlängern, was sich aber in der Regel erst während des Aufenthaltes zeigen  wird.<br />
    Die Spezielkurse haben eine Orientierung,  ausgerichtet nach den Programmen für die sich die Teilnehmer bei ihrer  Anmeldung aus ihrem Heimatland entschieden haben:<br />
    - Freiwilligenarbeit (siehe „Freiwilligenarbeit“)<br />
    - Studentenpraktikum<br />
    - Professionelles Praktikum (siehe „Fachpraktika“)<br />
    - Kultur-Spanisch für Menschen die sich die Zeit  nehmen können und Rentner <br />
    - Technisches (z.B. Agrar- und Weinindusrtie) und  Wirtschafts-Spanisch<br />
    - Spanisch für das Universitätsstudium</p>
  <p>Das  Kursangebot ist grundsätzlich mit Unterkunft verbunden. Sie können allerdings  nach Kategorien (siehe Unterkunft) wählen. </p>
  <p>Die  Anreise sollten Sie am Besten über ein Ihnen bekanntes Reisebüro erledigen,  kann aber natürlich auch in Eigenregie erfolgen. Trotzdem orientieren wir Sie  vom Zeitpunkt Ihrer Abreise und erledigen die gesamte Planung vom Ankunfts-  bzw. Zielflughafen bis zu Ihre Unterkunft (siehe Unterkunft). Sie erhalten bei  dieser Gelegenheit ausserdem umfassende Information zu Ihrem Vor-Ort-Aufenthalt  und den besten Weg von Ihrer Unterkunft bis GREEN FIELDS (Vademecum für  Mendoza).<br />
    Aus  Gründen der Dauer Ihres Aufenthaltes, der Notwendigkeit und der Vorteile eines  eventuellen Familienanschlusses, aber auch aus Gründen der Wahrung Ihrer  Privatsphäre bieten wir keine Unterkünfte in Hostels an. </p>
  <p>Als Vorbereitung auf eine  Freiwilligenarbeit, ein Fachpraktikum oder einen Universitätsbesuch ist ein  mindestens 4-wöchiger Intensiv-Spanischkurs in individuellem Einzelunterricht  vor Ort sehr empfehlenswert, damit auch Sprachanfänger die gewünschten  Anschlusstätigkeiten ohne Scheu beginnen können (siehe Freiwilligenarbeit bzw.  Gaststudent in einer Universitäts). </p>