<h3>Wirtschaftsbeziehungen</h3>
<p>Die  Importe aus Argentinien nach Deutschland wuchsen 2007 um rund 27% auf rd. USD  2.052 Mrd (2006: 1.616&nbsp; Mrd. USD). Die deutschen Exporte nach Argentinien  nahmen um 38% zu (2007: 2.352 Mrd. USD, zum Vergleich 2005: 1.297 Mrd. USD  und&nbsp; 2006:&nbsp;1,699 Mrd. USD). Damit liegt Deutschland bei den  argentinischen Wareneinfuhren an vierter Stelle hinter Brasilien, den USA und  China, bei den argentinischen Warenausfuhren an neunter Position. Dagegen ist  Argentinien sowohl bei den deutschen Exporten wie bei den Importen nur an 50.  Stelle platziert.<br>
Die  argentinischen Exporte nach Deutschland werden dominiert von Rohstoffen und  landwirtschaftlichen Erzeugnissen (herausragend:&nbsp; Fleisch und Fleischwaren  mit 20% sowie Kupfererze mit 19 % der Exporte). Deutschland ist der größte  Abnehmer argentinischen Rindfleischs in der EU. Weiterhin kommen beispielsweise  ca. 30% des von Deutschland eingeführten Honigs aus Argentinien.<br>
Bei den  argentinischen Importen aus Deutschland stehen traditionell industrielle  Erzeugnisse, insbesondere Fahrzeuge und Fahrzeugteile (2007: 27% , 2006:  24%),&nbsp; Maschinen (2007: 22%, 2006: 24%), sowie pharmazeutische und  chemische Erzeugnisse (14% der argentinischen Einfuhren) im Vordergrund.<br>
Buenos  Aires ist Sitz der Deutsch-Argentinischen Industrie- und Handelskammer, die  rund 500 Mitglieder zählt, und des Büros des Korrespondenten der Bundesagentur  für Außenwirtschaft. Ein Investitionsschutzabkommen zwischen Argentinien und  Deutschland ist seit November 1993 in Kraft. Seit 1978 besteht ein  Doppelbesteuerungsabkommen.<br>
Deutschland  hat als Land der Technologie Vorbildfunktion und wird als Partner geschätzt.  Daher auch die wachsende Bedeutung der bilateralen wissenschaftlich-technologischen  Zusammenarbeit (Rahmenabkommen vom 31.03.1969). 2007 hat das  Max-Planck-Institut beschlossen, sein weltweit erst zweites ausländisches  Partnerinstitut in Buenos Aires zu eröffnen (Biotechnologie). Weitere  Schwerpunkte der Zusammenarbeit sind: Meeres- und Antarktisforschung,  Geowissenschaften, Informationstechnologie sowie Umweltforschung und  -technologie.<br>
Das  laufende regionale Programm im Rahmen der technischen Zusammenarbeit (TZ) -  basierend auf dem TZ-Rahmenabkommen von 1976 - konzentriert sich auf  Desertifikationsbekämpfung und den Ressourcenschutz im Gebiet Gran Chaco  Sudamericano.&nbsp; Die derzeit sieben CIM-Experten in&nbsp; Argentinien  konzentrieren sich auf Energie- und Umweltaspekte im Lande.<br>
In  den letzten Jahren hat die Bundesregierung den Opfern von Überschwemmungen in  den Provinzen Santa Fé (2003 und 2007) und Chaco (2005) humanitäre Soforthilfe  zukommen lassen. </p>
(Quelle: Auswärtiges Amt)

<div class="backPage"><a href="#" onclick="Slider.slide({url: 'includes/argentinien.php'}, 1); return false;"><img src="images/button_back.png" alt="Volver" title="Volver" border="0" align="absmiddle" />&nbsp;Volver</a></div>
